# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  # app:
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   build:
  #     context: .
  #   entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
  #   ports:
  #     - 3001:3001
  #     - 3002:3002
  #   environment:
  #     - TRUST_PROXY_HEADER=1
  #     # - IS_CLOUD=1
  #     - DB_URL=postgres://postgres:password@postgres:5432/logto
  #     # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
  #     # Or, you can leverage it for local testing.
  #     - ENDPOINT=http://localhost:3001
  #     - ADMIN_ENDPOINT=http://localhost:3002/
  postgres:
    image: postgres:17-alpine
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
